### ISSUE TITLE
Can't get kitti dataset

### ISSUE THREAD

**Issue by mesakh123** [jiongger/carla-client#1]
Thank you for your repo,
     I was trying to get kitti dataset from your repo, but it looks like that you miss the lib module, it will be nice to try the lib though. thanks

**Comment by jiongger** [comment]
thanks for the attention, the lib module was ignored by git due to the default .gitignore file
the lib module will be uploaded soon

**Comment by mesakh123** [comment]
You are rock, thank you for your hard work. 
It works.
